# Site settings
title: therudes.com Communication Service
email: matt@mattrude.com
description: ""
url: "https://conference.therudes.com"
name: "conference.therudes.com"
baseurl: ""
destination: "/var/www/therudes.im"

owner_name: "Matt Rude"
owner_pgpkey: "0xc4909ee495b0761f"

xmpp-url: "therudes.com"
xmpp-conference-url: "conference.therudes.com"
fingerprint-sha1: "BD:32:61:05:5D:F2:1D:FC:9E:40:74:29:CC:37:98:60:B5:C6:7C:8B"
fingerprint-sha256: "C3:0E:A2:BF:1E:C5:C4:DD:E9:BE:10:1D:A1:F6:79:34:7C:FD:4A:CF:7F:73:22:16:CA:DC:F5:4C:59:A7:F8:1D"
fingerprint-conference-sha1: "35:3E:7B:63:89:B3:C6:6D:D7:32:70:C6:8B:27:92:A6:74:1C:98:96"
fingerprint-conference-sha256: "8F:54:F8:8B:C1:52:C3:40:E6:47:94:9D:DA:1E:1E:51:E5:92:FC:9F:79:A8:E3:2D:2E:84:1D:FC:F2:8B:7A:AD"
prosody-version: "0.10.0"

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- css/syntax.less
- css/site.less
- css/small.less

gems:
- jekyll-sitemap
- jekyll-minifier
#- jekyll-less
#- jekyll-press
#- jekyll-redirect-from
#- jekyll-last-modified-at

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
