# Site settings
title: mattrude.com Communication Service
email: matt@mattrude.com
description: ""
url: "https://im.mattrude.com"
name: "mattrude.com"
baseurl: "im.mattrude.com"
destination: "/root/xmpp-site/www/im.mattrude.com"

owner_name: "Matt Rude"
owner_pgpkey: "0xc4909ee495b0761f"

xmpp-url: "mattrude.com"
xmpp-host: "im.mattrude.com"
xmpp-conference-url: "conference.mattrude.com"
xmpp-proxy-url: "proxy.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)

xep-0163: 1 # Personal Eventing Protocal
xep-0237: 1 # Roster Versioning
xep-0280: 1 # Message Carbons
xep-0191: 1 # Blocking Command
xep-0045: 0 # Multi-User Chat
xep-0198: 1 # Stream Management
xep-0313: 1 # Message Archive Management
xep-0352: 1 # Client State Indication
xep-0363: 1 # HTTP File Upload
xep-0065: 0 # SOCKS 5 Bytestreams (Proxy)
xep-0357: 1 # Push Notifications
xep-0375: 0 # XMPP protocol compliance levels for 2016

fingerprints: 1
fingerprint-proxy: 1
fingerprint-conference: 0
fingerprint-expires: "May 30 16:34:00 2017 GMT"
fingerprint-conference-expires: "May 30 16:34:00 2017 GMT"
fingerprint-proxy-expires: "May 30 16:34:00 2017 GMT"
fingerprint-sha1: "F1:25:FD:E3:FA:A8:83:92:76:D6:C4:52:7F:01:52:BB:FB:82:C0:9A"
fingerprint-sha256: "FC:07:0F:0E:2D:ED:32:B3:6F:56:75:BF:15:E6:AF:E2:37:89:AC:1D:0B:42:AD:75:D3:1D:1D:C4:14:F7:EA:E6"
fingerprint-conference-sha1: "F1:25:FD:E3:FA:A8:83:92:76:D6:C4:52:7F:01:52:BB:FB:82:C0:9A"
fingerprint-conference-sha256: "FC:07:0F:0E:2D:ED:32:B3:6F:56:75:BF:15:E6:AF:E2:37:89:AC:1D:0B:42:AD:75:D3:1D:1D:C4:14:F7:EA:E6"
fingerprint-proxy-sha1: "F1:25:FD:E3:FA:A8:83:92:76:D6:C4:52:7F:01:52:BB:FB:82:C0:9A"
fingerprint-proxy-sha256: "FC:07:0F:0E:2D:ED:32:B3:6F:56:75:BF:15:E6:AF:E2:37:89:AC:1D:0B:42:AD:75:D3:1D:1D:C4:14:F7:EA:E6"
prosody-version: "0.10"

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- css/syntax.less
- css/site.less
- css/small.less

gems:
- jekyll-sitemap
- jekyll-less
#- jekyll-press
#- jekyll-redirect-from
#- jekyll-last-modified-at

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
