# Site settings
title: mattrude.com Communication Service
email: matt@mattrude.com
description: ""
url: "https://im.mattrude.com"
name: "mattrude.com"
baseurl: "im.mattrude.com"
#destination: "/root/xmpp-site/www/im.mattrude.com"
destination: "/var/www/im.mattrude.com"
prosody-version: "0.10"

owner_name: "Matt Rude"
owner_pgpkey: "0xc4909ee495b0761f"

xmpp-url: "mattrude.com" # The XMPP domain url
xmpp-host: "im.mattrude.com" # The hostname of the server
xmpp-conference-url: "conference.mattrude.com" # Multi-User Chat xep-0045
xmpp-proxy-url: "proxy.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)
xmpp-upload-url: "upload.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)

xep-0163: 1 # Personal Eventing Protocal
xep-0237: 1 # Roster Versioning
xep-0280: 1 # Message Carbons
xep-0191: 1 # Blocking Command
xep-0045: 1 # Multi-User Chat
xep-0198: 1 # Stream Management
xep-0313: 1 # Message Archive Management
xep-0352: 1 # Client State Indication
xep-0363: 1 # HTTP File Upload
xep-0065: 1 # SOCKS 5 Bytestreams (Proxy)
xep-0357: 1 # Push Notifications
xep-0375: 1 # XMPP protocol compliance levels for 2016

fingerprints: 1
fingerprint-expires: "Sep 23 00:01:00 2017 GMT"
fingerprint-im-expires: "Oct  1 06:08:00 2017 GMT"
fingerprint-conference-expires: "Oct  1 06:08:00 2017 GMT"
fingerprint-proxy-expires: "Oct  1 06:08:00 2017 GMT"
fingerprint-upload-expires: "Oct  1 06:08:00 2017 GMT"
fingerprint-sha1: "82:C5:78:0A:E3:23:BE:47:43:E6:B3:7B:7A:63:A3:34:98:98:CA:F5"
fingerprint-sha256: "0E:76:CB:50:2F:55:D1:7F:E5:A5:E4:15:41:E4:A5:A1:A4:96:CE:0E:9F:D8:29:1D:55:D9:36:F3:52:5A:C6:A4"
fingerprint-im-sha1: "4B:06:4B:69:C2:CF:C2:93:9C:10:33:7A:F7:1C:63:95:48:3C:E1:DE"
fingerprint-im-sha256: "03:15:EE:9F:F5:FF:B4:22:64:A2:82:69:2D:EB:FA:60:45:FE:F3:13:B1:5F:08:A9:8E:22:DE:91:FE:B0:B2:DF"
fingerprint-conference-sha1: "4B:06:4B:69:C2:CF:C2:93:9C:10:33:7A:F7:1C:63:95:48:3C:E1:DE"
fingerprint-conference-sha256: "03:15:EE:9F:F5:FF:B4:22:64:A2:82:69:2D:EB:FA:60:45:FE:F3:13:B1:5F:08:A9:8E:22:DE:91:FE:B0:B2:DF"
fingerprint-proxy-sha1: "4B:06:4B:69:C2:CF:C2:93:9C:10:33:7A:F7:1C:63:95:48:3C:E1:DE"
fingerprint-proxy-sha256: "03:15:EE:9F:F5:FF:B4:22:64:A2:82:69:2D:EB:FA:60:45:FE:F3:13:B1:5F:08:A9:8E:22:DE:91:FE:B0:B2:DF"
fingerprint-upload-sha1: "4B:06:4B:69:C2:CF:C2:93:9C:10:33:7A:F7:1C:63:95:48:3C:E1:DE"
fingerprint-upload-sha256: "03:15:EE:9F:F5:FF:B4:22:64:A2:82:69:2D:EB:FA:60:45:FE:F3:13:B1:5F:08:A9:8E:22:DE:91:FE:B0:B2:DF"

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- css/syntax.less
- css/site.less
- css/small.less

gems:
- jekyll-sitemap
#- jekyll-less
#- jekyll-press
#- jekyll-redirect-from
#- jekyll-last-modified-at

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
