# Site settings
title: mattrude.com Communication Service
email: matt@mattrude.com
description: ""
url: "https://im.mattrude.com"
name: "mattrude.com"
baseurl: "im.mattrude.com"
#destination: "/root/xmpp-site/www/im.mattrude.com"
destination: "/var/www/im.mattrude.com"
prosody-version: "0.10"

owner_name: "Matt Rude"
owner_pgpkey: "0xc4909ee495b0761f"

xmpp-url: "mattrude.com" # The XMPP domain url
xmpp-host: "im.mattrude.com" # The hostname of the server
xmpp-conference-url: "conference.mattrude.com" # Multi-User Chat xep-0045
xmpp-proxy-url: "proxy.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)
xmpp-upload-url: "upload.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)

xep-0163: 1 # Personal Eventing Protocal
xep-0237: 1 # Roster Versioning
xep-0280: 1 # Message Carbons
xep-0191: 1 # Blocking Command
xep-0045: 1 # Multi-User Chat
xep-0198: 1 # Stream Management
xep-0313: 1 # Message Archive Management
xep-0352: 1 # Client State Indication
xep-0363: 1 # HTTP File Upload
xep-0065: 1 # SOCKS 5 Bytestreams (Proxy)
xep-0357: 1 # Push Notifications
xep-0375: 1 # XMPP protocol compliance levels for 2016

fingerprints: 1
fingerprint-expires: "Jul 24 01:13:00 2017 GMT"
fingerprint-conference-expires: "Aug  2 02:40:00 2017 GMT"
fingerprint-proxy-expires: "Aug  2 02:40:00 2017 GMT"
fingerprint-upload-expires: "Aug  2 02:40:00 2017 GMT"
fingerprint-sha1: "2C:23:33:2A:CB:E2:B8:37:C7:43:D1:58:CF:4F:E3:5D:48:CB:1F:F7"
fingerprint-sha256: "B1:80:58:73:17:7C:5B:32:AB:86:9D:D1:21:62:E8:7B:00:70:8A:99:2A:A0:1E:E1:FC:FF:21:23:C7:EF:F5:3B"
fingerprint-conference-sha1: "BF:0C:47:3D:ED:C3:92:95:A8:86:B8:50:EB:21:4F:A7:A0:C5:D7:D0"
fingerprint-conference-sha256: "DF:71:7A:69:8E:10:34:AB:6B:CE:02:EC:41:CF:AE:0A:F8:B2:B4:D9:7D:58:7D:A8:7C:BA:F9:3B:50:FF:02:0F"
fingerprint-proxy-sha1: "BF:0C:47:3D:ED:C3:92:95:A8:86:B8:50:EB:21:4F:A7:A0:C5:D7:D0"
fingerprint-proxy-sha256: "DF:71:7A:69:8E:10:34:AB:6B:CE:02:EC:41:CF:AE:0A:F8:B2:B4:D9:7D:58:7D:A8:7C:BA:F9:3B:50:FF:02:0F"
fingerprint-upload-sha1: "BF:0C:47:3D:ED:C3:92:95:A8:86:B8:50:EB:21:4F:A7:A0:C5:D7:D0"
fingerprint-upload-sha256: "DF:71:7A:69:8E:10:34:AB:6B:CE:02:EC:41:CF:AE:0A:F8:B2:B4:D9:7D:58:7D:A8:7C:BA:F9:3B:50:FF:02:0F"

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- css/syntax.less
- css/site.less
- css/small.less

gems:
- jekyll-sitemap
- jekyll-press

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

theme: jekyll-theme-modernist